#'@export
cleanKP <- function(dat) {
  dat$TeamName <- gsub("St\\.", "State", dat$TeamName)
  dat$TeamName <- gsub("Mount State Mary's", "Mount St. Mary's", dat$TeamName)
  dat$TeamName <- gsub("Middle Tennessee", "Middle Tennessee State", dat$TeamName)
  dat$TeamName <- gsub("USC", "Southern California", dat$TeamName)
  dat$TeamName <- gsub("VCU", "Virginia Commonwealth", dat$TeamName)
  dat$TeamName <- gsub("SMU", "Southern Methodist", dat$TeamName)
  dat$TeamName <- gsub("Miami FL", "Miami (Fla.)", dat$TeamName)
  dat$TeamName <- gsub("Saint Joseph's", "St. Joseph's", dat$TeamName)
  dat$TeamName <- gsub("Little Rock", "Arkansas-Little Rock", dat$TeamName)
  dat$TeamName <- gsub("Arkansas Arkansas-Little Rock", "Arkansas-Little Rock", dat$TeamName)
  dat$TeamName <- gsub("BYU", "Brigham Young", dat$TeamName)
  dat$TeamName <- gsub("Albany", "Albany (N.Y.)", dat$TeamName)
  dat$TeamName <- gsub("Saint Mary's", "St. Mary's (Cal.)", dat$TeamName)
  dat$TeamName <- gsub("State John's", "St. John's", dat$TeamName)
  dat$TeamName <- gsub("UAB", "Alabama-Birmingham", dat$TeamName)
  dat$TeamName <- gsub("Louisiana Lafayette", "Louisiana-Lafayette", dat$TeamName)
  dat$TeamName <- gsub("Cal Poly", "Cal-Poly", dat$TeamName)
  dat$TeamName <- gsub("State Louis", "St. Louis", dat$TeamName)
  dat$TeamName <- gsub("Saint Louis", "St. Louis", dat$TeamName)
  dat$TeamName <- gsub("LIU Brooklyn", "Long Island", dat$TeamName)
  dat$TeamName <- gsub("Murray State", "Murray St.", dat$TeamName)
  dat$TeamName <- gsub("State Bonaventure", "St. Bonaventure", dat$TeamName)
  dat$TeamName <- gsub("Southern Miss", "Southern Mississippi", dat$TeamName)
  dat$TeamName <- gsub("Loyola MD", "Loyola (Md.)", dat$TeamName)
  dat$TeamName <- gsub("Saint Peter's", "St. Peter's", dat$TeamName)
  dat$TeamName <- gsub("UTSA", "Texas-San Antonio", dat$TeamName)
  dat$TeamName <- gsub("Arkansas Pine Bluff", "Arkansas-Pine Bluff", dat$TeamName)
  dat$TeamName <- gsub("UT Arlington", "Texas-Arlington", dat$TeamName)
  dat$TeamName <- gsub("UMBC", "Maryland-Baltimore County", dat$TeamName)
  dat$TeamName <- gsub("Miami OH", "Miami (Ohio)", dat$TeamName)
  dat$TeamName <- gsub("Texas A&M Corpus Chris", "Texas A&M-Corpus Christi", dat$TeamName)
  dat$TeamName <- gsub("Central Connecticut", "Central Connecticut State", dat$TeamName)
  dat$TeamName <- gsub("UCF", "Central Florida", dat$TeamName)
  dat$TeamName <- gsub("Illinois Chicago", "Illinois-Chicago", dat$TeamName)
  dat$TeamName <- gsub("Troy State", "Troy", dat$TeamName)
  return(dat)
}
